apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-frontend
spec:
  selector:
    matchLabels:
      app: flask-pod-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-pod-frontend
    spec:
      containers:
      - name: flask-frontend
        image: manish8757/rancher:7c0ba5dcad236b0393949eb17917995a015a5edd
        imagePullPolicy: Always
        ports:
        - containerPort: 5100          
