apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-frontend
spec:
  selector:
    matchLabels:
      app: flask-pod-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-pod-frontend
    spec:
      containers:
      - name: flask-backend
        image: manish8757/rancher:test
        imagePullPolicy: Never
        ports:
        - containerPort: 5100          
